#!/usr/bin/env python

import os
from val_description import InstanceFileHandler
import xml.etree.ElementTree as xmlParser
import argparse


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Apply torque offsets contained in file to coeff files for actuators on a robot described by an instance file.",
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    # top level args
    parser.add_argument("-o", "--offsets-file", type=str,
                        help="Full file path of the xml file containing the force offsets to be appliced")
    parser.add_argument("-i", "--instance-file", type=str,
                        help="Full file path to the instance file for the robot containing the actuators to which the offsets will be applied")

    args = parser.parse_args()

    if not args.instance_file:
        raise Exception("You MUST supply an instance file via the -i argument!")

    if not args.offsets_file:
        raise Exception("You MUST supply a file containing force offsets via the -o argument!")

    instanceFilePath = args.instance_file
    offsetsFile = xmlParser.parse(args.offsets_file)
    instanceFileHandler = InstanceFileHandler.InstanceFileHandler(instanceFilePath)

    # valDescriptionPackagePath = os.getenv('VAL_WORKSPACE') + '/src/val_description'
    # actuatorCoeffFilePaths = self.valDescriptionPackagePath + '/instance/coefficients/actuators/'
